import { Document, Page, View, Text } from "@react-pdf/renderer";
import { format, getTime } from "date-fns";
import React from "react";
import { performanceData } from "../types";
import styles from "./report_templates/styles";
import moment from "moment";
import { formatNumber } from "../../Commons";
const TresurerReport: React.FC<{ data: performanceData }> = ({ data }) => {
  return (
    <Document>
      <Page size={"A4"} style={{ display: "flex", flexDirection: "column" }}>
        <View style={styles.header} fixed>
          <Text style={styles.title}>Account Summary</Text>
          <View style={styles.location}>
            <Text>https://jirainibora.com</Text>
            <Text>info@jiranibora.com</Text>
            <Text>+254796407365</Text>
          </View>
          <View style={styles.location}>
            <Text>Busia Road, Off Enterprise Road,</Text>
            <Text>00500,</Text>
            <Text>Nairobi, Kenya.</Text>
          </View>
        </View>
        <View style={styles.metadata}>
          <View style={styles.metadataContainer}>
            <View>
              <Text style={styles.metadesc}>Generated By</Text>
              <Text style={styles.metadataContent}>Treasurer</Text>
            </View>
            <View>
              <Text style={styles.metadesc}>Name</Text>
              <Text style={styles.metadataContent}>{data.sender}</Text>
            </View>
          </View>
          <View style={styles.metadataContainer}>
            <View>
              <Text style={styles.metadesc}>Document Date</Text>
              <Text style={styles.metadataContent}>
                {moment().format("LL")}
              </Text>
            </View>
            <View>
              <Text style={styles.metadesc}>Time</Text>
              <Text style={styles.metadataContent}>
                {moment().format("LT")}
              </Text>
            </View>
          </View>
          <View style={{ ...styles.metadataContainer }}>
            <View>
              <Text style={styles.metadesc}>Total Members</Text>
              <Text style={{ ...styles.members, color: "dodgerblue" }}>
                {data.members.active + data.members.dormant}
              </Text>
            </View>
            <View
              style={{
                display: "flex",
                flexDirection: "row",
                justifyContent: "space-between",
              }}
            >
              <View style={styles.memberdesc}>
                <Text style={styles.metadesc}>Active</Text>
                <Text
                  style={{
                    ...styles.metadataContent,
                    fontSize: "15px",
                    color: "#008838",
                  }}
                >
                  {data.members.active}
                </Text>
              </View>
              <View style={{ fontSize: "15px" }}>
                <Text style={styles.metadesc}>Dormant</Text>
                <Text
                  style={{
                    ...styles.metadataContent,
                    fontSize: "15px",
                    color: "red",
                  }}
                >
                  {data.members.dormant}
                </Text>
              </View>
            </View>
          </View>
        </View>
        <View style={styles.body}>
          <View
            style={{
              backgroundColor: "#008838",
              height: "2px",
              marginBottom: "20px",
            }}
          ></View>
          <Text
            style={{
              color: "#008838",
              fontWeight: "bold",
              fontSize: "20px",
              textAlign: "center",
              marginBottom: "20px",
            }}
          >
            Jirani Bora Summary Statement
          </Text>
          <View id="table" style={styles.table}>
            <View
              style={{
                ...styles.tableRow,
                backgroundColor: "#008838",
                color: "white",
                borderColor: "#d3d3d3",
              }}
            >
              <Text
                style={{
                  ...styles.tableColumn,
                  width: "70%",
                  fontSize: "15px",
                  padding: "5px",
                  borderColor: "#d3d3d3",
                }}
              >
                Description
              </Text>
              <Text
                style={{
                  ...styles.tableColumn,
                  width: "30%",
                  fontSize: "15px",
                  padding: "5px",
                  borderColor: "#008838",
                }}
              >
                Amount (KES)
              </Text>
            </View>
            {data.data.length > 0 &&
              data !== null &&
              data.data.map((each, index) => {
                return (
                  <View style={styles.tableRow} key={each.description}>
                    <Text
                      style={{
                        ...styles.tableColumn,
                        width: "70%",
                        fontSize: "13px",
                        padding: "10px",
                        fontWeight: "light",
                      }}
                    >
                      {each.description}
                    </Text>
                    <Text
                      style={{
                        ...styles.tableColumn,
                        width: "30%",
                        fontSize: "13px",
                        padding: "10px",
                        fontWeight: "light",
                      }}
                    >
                      {formatNumber(each.value)}
                    </Text>
                  </View>
                );
              })}
          </View>
        </View>
        <View fixed style={styles.footer}>
          <Text>Jirani Bora Savings And Credit</Text>
          <Text>&copy; 2022</Text>
        </View>
      </Page>
    </Document>
  );
};

export default TresurerReport;
